"""ad new field

Revision ID: c40ab502c8d0
Revises: 
Create Date: 2025-09-24 06:21:31.801945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40ab502c8d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('description', sa.String(), nullable=True))
    op.add_column('students', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'students', ['email'])
    op.add_column('teachers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('phone', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'teachers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_column('teachers', 'phone')
    op.drop_column('teachers', 'email')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'email')
    op.drop_column('students', 'age')
    op.drop_column('courses', 'description')
    # ### end Alembic commands ###
